language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.1
  - 2.2
  - 2.1
  - 2.0.0
  - jruby-head
  - ruby-head
env:
  global:
    - JRUBY_OPTS="-J-Xmx1024M --debug"
matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
