bundler_args: --retry=3 --jobs=3
cache: bundler
language: ruby
sudo: false
rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - jruby
  - jruby-head
  - jruby-9.0.0.0.pre1
  - rbx-2
  - ruby-head
env:
  global:
    - JRUBY_OPTS="-J-Xmx1024M --debug"
matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: jruby
    - rvm: jruby-head
    - rvm: jruby-9.0.0.0.pre1
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true
